# Add this lines if not exist

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/stack-in-card/stack-in-card.js
    type: module
  - url: /hacsfiles/lovelace-mushroom/mushroom.js
    type: module
  dashboards:
    lovelace-counters: # Needs to contain a hyphen (-)
      mode: yaml
      filename: /config/lovelace/electro_counters_lovelace.yaml
      title: Счётчики
      icon: mdi:counter
      show_in_sidebar: true
      require_admin: false

homeassistant:
  packages: !include_dir_merge_named includes/packages/
